FROM ubuntu:24.04
SHELL ["/bin/bash", "-c"]

ARG VER_SGLANG=qwen3_support

RUN apt-get update && \
    apt-get full-upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates \
    git \
    curl \
    wget \
    vim \
    libnuma-dev \
    gcc \
    g++ \
    make

WORKDIR /root

RUN curl -fsSL -v -o miniforge.sh -O https://github.com/conda-forge/miniforge/releases/download/24.11.3-2/Miniforge3-24.11.3-2-Linux-x86_64.sh && \
    bash miniforge.sh -b -p ./miniforge3 && \
    rm -f miniforge.sh && \
    . miniforge3/bin/activate && \
    conda install -y libsqlite=3.48.0 gperftools tbb libnuma numactl

ENV PATH=/root/miniforge3/bin:/root/miniforge3/condabin:${PATH}
ENV PIP_ROOT_USER_ACTION=ignore
ENV CONDA_PREFIX=/root/miniforge3

RUN pip config set global.extra-index-url https://pypi.org/simple && \
    pip install cmake==3.31.2 \
    "setuptools-scm>=8" \
    intel-openmp==2024.2.0

RUN git clone https://github.com/pratima-intel/sglang.git && \
    cd sglang && \
    cp ../torchao_utils.py ./python/sglang/srt/layers/ && \
    git checkout ${VER_SGLANG} && \
    pip install -e "python[all_cpu]" && \
    pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu && \
    cd sgl-kernel && \
    python setup.py install

ENV LD_PRELOAD=/root/miniforge3/lib/libiomp5.so:/root/miniforge3/lib/libtcmalloc.so:/root/miniforge3/lib/libtbbmalloc.so.2

WORKDIR /root/sglang
